export function extractEventFormRaw(formData: FormData) {
  return {
    title: String(formData.get("title") ?? ""),
    description: String(formData.get("description") ?? ""),
    categories: formData.getAll("categories").map(String),
    startAt: String(formData.get("startAt") ?? ""),
    endAt: String(formData.get("endAt") ?? ""),
    isRecurring: formData.get("isRecurring") === "true",
    recurrenceRule: String(formData.get("recurrenceRule") ?? ""),
    venueName: String(formData.get("venueName") ?? ""),
    addressLine1: String(formData.get("addressLine1") ?? ""),
    city: String(formData.get("city") ?? ""),
    state: String(formData.get("state") ?? ""),
    zip: String(formData.get("zip") ?? ""),
    latitude: String(formData.get("latitude") ?? ""),
    longitude: String(formData.get("longitude") ?? ""),
    indoorOutdoor: String(formData.get("indoorOutdoor") ?? "INDOOR"),
    isFree: formData.get("isFree") === "true",
    price: String(formData.get("price") ?? ""),
    ticketUrl: String(formData.get("ticketUrl") ?? ""),
    minAge: String(formData.get("minAge") ?? ""),
    maxAge: String(formData.get("maxAge") ?? ""),
    coverImageUrl: String(formData.get("coverImageUrl") ?? ""),
    accessibilityContactName: String(formData.get("accessibilityContactName") ?? ""),
    accessibilityContactEmail: String(formData.get("accessibilityContactEmail") ?? ""),
    accessibilityContactPhone: String(formData.get("accessibilityContactPhone") ?? ""),
  };
}
